### ISSUE TITLE
Changing the name of an app doesn't change the title

### ISSUE THREAD

**Issue by fpliger** [anaconda/pyscript-hackathon#15] opened 2023-01-19 18:32 UTC
If you create a new app and change the name after, the app title on the deployed application page remains as the original name.

To reproduce:

* create a new app
* change it's name
* navigate to the deployed app and see that the title remains as the old one

**Comment by madhur-tandon** [comment] 2023-01-24 16:18
This is a duplicate of https://github.com/anaconda/pyscript-hackathon/issues/14 😅

**Comment by tedpatrick** [comment] 2023-01-27 10:52
duplicate closing

**Closed as completed by tedpatrick** 2023-01-27 10:52 UTC
Labels: bug
